default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: admin
  password: secret
  pool: 5

development:
  <<: *default
  database: mydb_dev
  port: 5432

test:
  <<: *default
  database: mydb_test
  port: 5432


production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
